spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
    username: admin
    password: password
    driver-class-name: org.h2.Driver
    initialize: true
    initialize-mode: always
